## 資料預處理　（Data Preprocessing)

### 1. 缺失值處理(Missing data)
* 丟棄 (PS. 如資料量夠多)
* 補值

### 1.1 丟棄缺失值

In [6]:
from pandas import read_csv
df = read_csv('1.csv')
df

A     B     C     D     E   F
0  10.0  20.0  30.0  40.0  50.0 NaN
1  11.0   NaN   NaN  41.0  51.0 NaN
2  12.0  22.0  32.0  42.0  52.0 NaN
3   NaN   NaN   NaN   NaN   NaN NaN
4  13.0  22.0   NaN  43.0  53.0 NaN
5  14.0   NaN  34.0  44.0  54.0 NaN

In [7]:
#判斷是否有缺失值
df.isnull()

A      B      C      D      E     F
0  False  False  False  False  False  True
1  False   True   True  False  False  True
2  False  False  False  False  False  True
3   True   True   True   True   True  True
4  False  False   True  False  False  True
5  False   True  False  False  False  True

In [8]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D, E, F]
Index: []

In [9]:
df

A     B     C     D     E   F
0  10.0  20.0  30.0  40.0  50.0 NaN
1  11.0   NaN   NaN  41.0  51.0 NaN
2  12.0  22.0  32.0  42.0  52.0 NaN
3   NaN   NaN   NaN   NaN   NaN NaN
4  13.0  22.0   NaN  43.0  53.0 NaN
5  14.0   NaN  34.0  44.0  54.0 NaN

In [10]:
# 全為空時刪除
df.dropna(how = 'all', axis=0)

A     B     C     D     E   F
0  10.0  20.0  30.0  40.0  50.0 NaN
1  11.0   NaN   NaN  41.0  51.0 NaN
2  12.0  22.0  32.0  42.0  52.0 NaN
4  13.0  22.0   NaN  43.0  53.0 NaN
5  14.0   NaN  34.0  44.0  54.0 NaN

In [11]:
df.dropna(how = 'all', axis=1)

A     B     C     D     E
0  10.0  20.0  30.0  40.0  50.0
1  11.0   NaN   NaN  41.0  51.0
2  12.0  22.0  32.0  42.0  52.0
3   NaN   NaN   NaN   NaN   NaN
4  13.0  22.0   NaN  43.0  53.0
5  14.0   NaN  34.0  44.0  54.0

In [12]:
# 某一欄為空時刪除
df.dropna(subset=['B'])

A     B     C     D     E   F
0  10.0  20.0  30.0  40.0  50.0 NaN
2  12.0  22.0  32.0  42.0  52.0 NaN
4  13.0  22.0   NaN  43.0  53.0 NaN

範例資料集 : Kaggle 's pima-indians-diabetes.csv

https://www.kaggle.com/kumargh/pimaindiansdiabetescsv/version/1#_=_

Fields description follow:

Field | 中文說明
---|---
preg |懷孕次數
plas |血漿葡萄糖濃度
pres |舒張壓
skin |肱三頭肌皮膚褶皺厚度
test |2小時血清胰島素
mass |體重指數 BMI
pedi | 糖尿病譜系功能
age | 年齡 
class |類別變量（1：糖尿病檢測陽性，0：糖尿病檢測陰性）

In [13]:
from pandas import read_csv
data = read_csv('pima-indians-diabetes.csv',header=None)
data.describe()

0           1           2           3           4           5  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

                6           7           8  
count  768.000000  768.000000  768.000000  
mean     0.471876   33.240885    0.348958  
std      0.331329   11.760232    0.476951  
min      0.078000   21.000000    0.000000  
25%      0.243750   24.000000    0.000000  
50%      0.372500   29.000000    0.000000  
75%      0.626250   41.000000    1.000000  
max      2.420000   81.000000    1.000000

In [14]:
data.head(10)

0    1   2   3    4     5      6   7  8
0   6  148  72  35    0  33.6  0.627  50  1
1   1   85  66  29    0  26.6  0.351  31  0
2   8  183  64   0    0  23.3  0.672  32  1
3   1   89  66  23   94  28.1  0.167  21  0
4   0  137  40  35  168  43.1  2.288  33  1
5   5  116  74   0    0  25.6  0.201  30  0
6   3   78  50  32   88  31.0  0.248  26  1
7  10  115   0   0    0  35.3  0.134  29  0
8   2  197  70  45  543  30.5  0.158  53  1
9   8  125  96   0    0   0.0  0.232  54  1

In [15]:
(data[[1,2,3,4,5]]==0).sum()

1      5
2     35
3    227
4    374
5     11
dtype: int64

In [16]:
#以NaN 取代 0 或無意義值

import numpy as np
data[[1,2,3,4,5]] = data[[1,2,3,4,5]].replace(0,np.NaN)
data.isnull().sum()


0      0
1      5
2     35
3    227
4    374
5     11
6      0
7      0
8      0
dtype: int64

In [17]:
data[[1,2,3,4,5]] = data[[1,2,3,4,5]].replace(0,np.NaN)
data.isnull().sum()

0      0
1      5
2     35
3    227
4    374
5     11
6      0
7      0
8      0
dtype: int64

In [18]:
data.head(10)

0      1     2     3      4     5      6   7  8
0   6  148.0  72.0  35.0    NaN  33.6  0.627  50  1
1   1   85.0  66.0  29.0    NaN  26.6  0.351  31  0
2   8  183.0  64.0   NaN    NaN  23.3  0.672  32  1
3   1   89.0  66.0  23.0   94.0  28.1  0.167  21  0
4   0  137.0  40.0  35.0  168.0  43.1  2.288  33  1
5   5  116.0  74.0   NaN    NaN  25.6  0.201  30  0
6   3   78.0  50.0  32.0   88.0  31.0  0.248  26  1
7  10  115.0   NaN   NaN    NaN  35.3  0.134  29  0
8   2  197.0  70.0  45.0  543.0  30.5  0.158  53  1
9   8  125.0  96.0   NaN    NaN   NaN  0.232  54  1

### 1.2 補值

* 定值0、平均數、眾數、中位數

In [19]:
from pandas import read_csv
df = read_csv('1.csv')
df

A     B     C     D     E   F
0  10.0  20.0  30.0  40.0  50.0 NaN
1  11.0   NaN   NaN  41.0  51.0 NaN
2  12.0  22.0  32.0  42.0  52.0 NaN
3   NaN   NaN   NaN   NaN   NaN NaN
4  13.0  22.0   NaN  43.0  53.0 NaN
5  14.0   NaN  34.0  44.0  54.0 NaN

In [20]:
df.fillna(0)
#df.fillna(value=10)

A     B     C     D     E    F
0  10.0  20.0  30.0  40.0  50.0  0.0
1  11.0   0.0   0.0  41.0  51.0  0.0
2  12.0  22.0  32.0  42.0  52.0  0.0
3   0.0   0.0   0.0   0.0   0.0  0.0
4  13.0  22.0   0.0  43.0  53.0  0.0
5  14.0   0.0  34.0  44.0  54.0  0.0

In [21]:
print(df['B'].mean())
#print(type(df['B'].mean()))
df

21.333333333333332


A     B     C     D     E   F
0  10.0  20.0  30.0  40.0  50.0 NaN
1  11.0   NaN   NaN  41.0  51.0 NaN
2  12.0  22.0  32.0  42.0  52.0 NaN
3   NaN   NaN   NaN   NaN   NaN NaN
4  13.0  22.0   NaN  43.0  53.0 NaN
5  14.0   NaN  34.0  44.0  54.0 NaN

In [22]:
# 使用 Pandas fillna() 補平均值

df['B'] = df['B'].fillna(df['B'].mean())
df

A          B     C     D     E   F
0  10.0  20.000000  30.0  40.0  50.0 NaN
1  11.0  21.333333   NaN  41.0  51.0 NaN
2  12.0  22.000000  32.0  42.0  52.0 NaN
3   NaN  21.333333   NaN   NaN   NaN NaN
4  13.0  22.000000   NaN  43.0  53.0 NaN
5  14.0  21.333333  34.0  44.0  54.0 NaN

In [23]:
from pandas import read_csv
df = read_csv('1.csv')
df

A     B     C     D     E   F
0  10.0  20.0  30.0  40.0  50.0 NaN
1  11.0   NaN   NaN  41.0  51.0 NaN
2  12.0  22.0  32.0  42.0  52.0 NaN
3   NaN   NaN   NaN   NaN   NaN NaN
4  13.0  22.0   NaN  43.0  53.0 NaN
5  14.0   NaN  34.0  44.0  54.0 NaN

In [24]:
print(df['B'].mode())
#print(type(df['B'].mode()))
df

0    22.0
dtype: float64


A     B     C     D     E   F
0  10.0  20.0  30.0  40.0  50.0 NaN
1  11.0   NaN   NaN  41.0  51.0 NaN
2  12.0  22.0  32.0  42.0  52.0 NaN
3   NaN   NaN   NaN   NaN   NaN NaN
4  13.0  22.0   NaN  43.0  53.0 NaN
5  14.0   NaN  34.0  44.0  54.0 NaN

In [25]:
# 使用 Pandas fillna() 補眾數

df['B'] = df['B'].fillna(df['B'].mode()[0])


In [26]:
df

A     B     C     D     E   F
0  10.0  20.0  30.0  40.0  50.0 NaN
1  11.0  22.0   NaN  41.0  51.0 NaN
2  12.0  22.0  32.0  42.0  52.0 NaN
3   NaN  22.0   NaN   NaN   NaN NaN
4  13.0  22.0   NaN  43.0  53.0 NaN
5  14.0  22.0  34.0  44.0  54.0 NaN

#### 1.2.1 Imputer

* 可選引數

strategy:  'mean'(預設的)， ‘median’中位數，‘most_frequent’出現頻率最大的數

* 輸出

numpy陣列，之後可轉化為DataFrame形式 
屬性： 

Imputer.statistics_可以檢視每列的均值/中位數

In [27]:
from pandas import read_csv
data = read_csv('1.csv')
data

A     B     C     D     E   F
0  10.0  20.0  30.0  40.0  50.0 NaN
1  11.0   NaN   NaN  41.0  51.0 NaN
2  12.0  22.0  32.0  42.0  52.0 NaN
3   NaN   NaN   NaN   NaN   NaN NaN
4  13.0  22.0   NaN  43.0  53.0 NaN
5  14.0   NaN  34.0  44.0  54.0 NaN

In [28]:
from sklearn.preprocessing import Imputer
import pandas as pd
#imputer=Imputer(strategy='mean')  # 使用平均數補植
#imputer=Imputer(strategy='median') # 使用中位數補植 
imputer=Imputer(strategy='most_frequent') # 使用出現頻率最大的數補植
imputer.fit(data)
X =imputer.transform(data)  #轉換結果X是一個numpy陣列
x =pd.DataFrame(X) #將numpy陣列轉化為dataframe

print(imputer.statistics_)  #檢視每個屬性平均值/中位數/重數

x.isnull().sum()

[10. 22. 30. 40. 50. nan]


0    0
1    0
2    0
3    0
4    0
dtype: int64

In [29]:
x

0     1     2     3     4
0  10.0  20.0  30.0  40.0  50.0
1  11.0  22.0  30.0  41.0  51.0
2  12.0  22.0  32.0  42.0  52.0
3  10.0  22.0  30.0  40.0  50.0
4  13.0  22.0  30.0  43.0  53.0
5  14.0  22.0  34.0  44.0  54.0

### 2. 類別資料處理

* 有序類別資料  EX :　XL,L,M,S,XS　=> 使用 Mapping 方式進行數值轉換
* 無序類別資料　EX :  Red,Blue,Yellow,Green　 => 使用One-hot encoding 

In [30]:
import pandas as pd

data = pd.DataFrame([['red','M',100],['yellw','L',120],['blue','S',80],['red','XL',150],['green','XL',150]])
data.columns=['Color','Size','Price']
data

Color Size  Price
0    red    M    100
1  yellw    L    120
2   blue    S     80
3    red   XL    150
4  green   XL    150

In [31]:
# 有序類別資料

Mapping_size = {
    'S' : 1,
    'M' : 2,
    'L' : 3,
    'XL' : 4   
}

data['Size'] = data['Size'].map(Mapping_size)
data


Color  Size  Price
0    red     2    100
1  yellw     3    120
2   blue     1     80
3    red     4    150
4  green     4    150

In [32]:
# One-hot encoding : Pandas' get_dummies function

print(pd.get_dummies(data['Color']))


   blue  green  red  yellw
0     0      0    1      0
1     0      0    0      1
2     1      0    0      0
3     0      0    1      0
4     0      1    0      0


In [33]:
onehot_encoding = pd.get_dummies(data['Color'],prefix= 'Color')

data = data.drop('Color',1)
data

Size  Price
0     2    100
1     3    120
2     1     80
3     4    150
4     4    150

In [34]:
pd.concat([onehot_encoding,data],axis=1)

Color_blue  Color_green  Color_red  Color_yellw  Size  Price
0           0            0          1            0     2    100
1           0            0          0            1     3    120
2           1            0          0            0     1     80
3           0            0          1            0     4    150
4           0            1          0            0     4    150

In [35]:
# Scikit-learn Onehot_encoding

data = pd.DataFrame([['red','M',100],['yellw','L',120],['blue','S',80],['red','XL',150],['green','XL',150]])
data.columns=['Color','Size','Price']
data

Color Size  Price
0    red    M    100
1  yellw    L    120
2   blue    S     80
3    red   XL    150
4  green   XL    150

In [36]:
from sklearn.preprocessing import LabelEncoder # LabelEncoder : Encode labels with value between 0 and n_classes-1.
from sklearn.preprocessing import OneHotEncoder # OneHotEncoder :  Encode categorical integer features as a one-hot numeric array.

le_color = LabelEncoder().fit(data['Color'])
print(le_color.classes_)

# le_num = LabelEncoder().fit([1, 2, 2, 6])
# print(le_num.classes_)



['blue' 'green' 'red' 'yellw']


In [37]:
color_label = le_color.transform(data['Color']) #轉換成數字組合表示
color_label

array([2, 3, 0, 2, 1])

In [38]:
le_color.inverse_transform([1, 0, 2, 1]) #還原承成顏色標籤資料

/home/user/.local/lib/python3.5/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


array(['green', 'blue', 'red', 'green'], dtype=object)

In [39]:
ohe_color = OneHotEncoder(sparse=False).fit(color_label.reshape(-1,1)) # sparse=False -> 不回傳一個稀疏矩陣
ohe_color

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=False)

In [40]:
Color_ohe = ohe_color.transform(color_label.reshape(-1,1))
Color_ohe

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.]])

### 3. 特徵縮放處理

特徵縮放是用來限制變數範圍的方法，以便能在相同的尺度上進行比較

#### 3.1 Standardization (標準化)
* 當單個特徵的樣本取值相差甚大或明顯不符合常態分佈時，標準化表現的效果較差。 =>移除每個特徵均值，劃分離散特徵的標準差 
* z-score 法
* 資料平均值=> 0, 標準差=>1
* 符合常態分佈，不會有偏單邊情況
* 降低離群值(outlier)對model的影響

In [41]:
import numpy as np

X = np.array([[ 10., -10.,  20.],
              [ 20.,  0.,  0.],
              [ 0.,  10., -10.]])

# X = np.array([[ 1., -1.,  2.],
#               [ 2.,  0.,  0.],
#               [ 0.,  1., -1.]])
# calculate mean
X_mean = X.mean(axis=0)
# calculate variance 
X_std = X.std(axis=0)
# standardize X
X1 = (X-X_mean)/X_std


In [42]:
X_mean

array([10.        ,  0.        ,  3.33333333])

In [43]:
X_std

array([ 8.16496581,  8.16496581, 12.47219129])

In [44]:
X1

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [45]:
# scale 
## sklearn.preprocessing.scale(X, axis=0, with_mean=True,with_std=True,copy=True)

from sklearn import preprocessing
import numpy as np

X = [[ 10., -10.,  20.],[ 20.,  0.,  0.],[ 0.,  10., -10.]]
scaler = preprocessing.scale(X)
scaler

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [46]:
scaler.mean(axis=0)  # axis=1表示對每一行進行操作，axis=0表示對每一列進行操作

array([0., 0., 0.])

In [47]:
scaler.std(axis=0)  # axis=1表示對每一行進行操作，axis=0表示對每一列進行操作

array([1., 1., 1.])

In [48]:
from sklearn import preprocessing
import numpy as np

X = [[ 10., -10.,  20.],[ 20.,  0.,  0.],[ 0.,  10., -10.]]

#使用sklearn.preprocessing.StandardScaler可 以在训练資料集上做標準化轉化操作後, 把相同轉換套到新的測試資料中
scaler = preprocessing.StandardScaler().fit(X) 
#scaler = preprocessing.StandardScaler(with_mean = False,with_std= False).fit(X) 
scaler
    

StandardScaler(copy=True, with_mean=True, with_std=True)

In [49]:
scaler.transform(X) 

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [50]:
scaler.mean_

array([10.        ,  0.        ,  3.33333333])

In [51]:
scaler.scale_

array([ 8.16496581,  8.16496581, 12.47219129])

In [52]:
#相同轉換套到新的測試資料中
new_x = [[-1., 1., 0.]]
scaler.transform(new_x ) 

array([[-1.34721936,  0.12247449, -0.26726124]])

#### 3.2  區間縮放
將特徵資料按比例縮放，讓資料落在某一特定的區間

#### MinMaxScaler

給定一個最大值/ 最小值的區間進行縮放

* X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

* X_scaled = X_std / (max - min) + min

In [53]:
# MinMaxScaler
from sklearn import preprocessing
import numpy as np

X = [[ 10., -10.,  20.],[ 20.,  0.,  0.],[ 0.,  10., -10.]]
min_max_scaler = preprocessing.MinMaxScaler(feature_range=(-1, 1)) 
#min_max_scaler = preprocessing.MinMaxScaler(feature_range=(5, 15)) 
result = min_max_scaler.fit_transform(X) 
result

array([[ 0.        , -1.        ,  1.        ],
       [ 1.        ,  0.        , -0.33333333],
       [-1.        ,  1.        , -1.        ]])

#### MaxAbsScaler
將資料特徵縮放到[-1,1]中間 => 所有資料除以最大值


In [54]:
from sklearn import preprocessing
import numpy as np

X = [[ 10., -10.,  20.],[ 20.,  0.,  0.],[ 0.,  10., -10.]]
MaxAbs_scaler = preprocessing.MaxAbsScaler() 
result = MaxAbs_scaler.fit_transform(X) 
result

array([[ 0.5, -1. ,  1. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  1. , -0.5]])

#### ˇ3.3 二值化 
將數值型的特徵資料轉換成Boolean值

In [55]:
from sklearn import preprocessing
import numpy as np

X = [[ 0., -1.,  2.],[ 2.,  1.,  0.],[ 0.,  1., -1.]]
binarizer = preprocessing.Binarizer().fit(X)
result = binarizer.fit_transform(X) 
result



array([[0., 0., 1.],
       [1., 1., 0.],
       [0., 1., 0.]])

In [56]:
from sklearn import preprocessing
import numpy as np
X = [[ 0., -1.,  2.],[ 2.,  1.,  0.],[ 0.,  1., -1.]]
binarizer = preprocessing.Binarizer(threshold=1.5)
result = binarizer.transform(X)
result

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 0.]])

### 4.資料降維

###  PCA (Principal Component Analysis)

In [58]:
import numpy as np
data = np.array([[ 1.  ,  1.  ],[ 0.9 ,  0.95],[ 1.01,  1.03],[ 2.  ,  2.  ], [ 2.03,  2.06],[ 1.98,  1.89],[ 3.  ,  3.  ],[ 3.03,  3.05],
       [ 2.89,  3.1 ],[ 4.  ,  4.  ],[ 4.06,  4.02],[ 3.97,  4.01]])

data

array([[1.  , 1.  ],
       [0.9 , 0.95],
       [1.01, 1.03],
       [2.  , 2.  ],
       [2.03, 2.06],
       [1.98, 1.89],
       [3.  , 3.  ],
       [3.03, 3.05],
       [2.89, 3.1 ],
       [4.  , 4.  ],
       [4.06, 4.02],
       [3.97, 4.01]])

sklearn.decomposition.PCA(n_components=None, copy=True, whiten=False)

參數|說明
------|------
n_components|需要保留的主成分個數N
copy|是否在運算時，將原始訓練數據複製一份
whiten | 使每個特徵具有相同的方差

In [59]:
from sklearn.decomposition import PCA 
pca=PCA(n_components=1)
newData=pca.fit_transform(data)
print(newData)

[[ 2.12015916]
 [ 2.22617682]
 [ 2.09185561]
 [ 0.70594692]
 [ 0.64227841]
 [ 0.79795758]
 [-0.70826533]
 [-0.76485312]
 [-0.70139695]
 [-2.12247757]
 [-2.17900746]
 [-2.10837406]]
